### ISSUE TITLE
反馈bug和建议，内存中新增金手指代码时寻址的问题

### ISSUE THREAD

**Issue by wzsx150** [zzpong/Interactive-ASM-Cheats-Updater#10]
<img width="1052" alt="bug反馈" src="https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/19254531/75f5dd7c-24d7-41c6-956b-f3222d366167">

大佬你好，非常感谢的你工具，对于金手指更新确实可以省劲非常多。
在使用过程中发现一个bug，就是当金手指代码是往内存中写内容时，会出现我截图的这个bug，生成的新代码变成了：

```
040B0000 07DE8EE8 3944EA68
040B0000 07DE8EEC 7100811F
040B0000 07DE8EF0 C0C6BLC0C7O4
040B0000 07DE8EF4 BD40BF0B
```

1、很显然这里的“C0C6BLC0C7O4”是有问题的，希望大佬修复。

2、另外，如果后面的金手指代码有其他标签调用这些地址段的代码时，就会识别不到，比如：
```
[攻击力2倍]
040B0000 0420F1DC 94EF66F7
040B0000 07DE4238 00000002
```
当然，我理解他们不在一个标签里，所以可能程序不会解析。
关于这个，建议大佬增加一个可勾选选项，就是跨标签识别新增的内存地址（不在程序已有代码段的地址），这样兼容性会更强。

3、建议增加一个一键生成的按钮，这样不需要人一直点，直接默认生成出来所有结果，然后完整的日志可以保存或者查看。这样效率会高很多，有问题看完整日志，再针对性的查看和处理。

最后再次感谢大佬！

**Comment by zzpong** [comment]
感谢你的反馈建议~

1. “C0C6BLC0C7O4”为金手指地址标记位，目的就是为了解决你所说的2中所提到的问题。这种标记位在对应地址更新后会自动更新为正确地址。如果生成到最后也没有变回正常地址的话，那就是对应地址定位新位置失败，这部分代码也就可以删除了。

2. 跨标签的问题请参考问题1的回复。

3. 考虑到部分金手指生成过程必须用户决策，比如同时定位到两个地址、内存修改指令是否直接复制等，因此并没有一键生成功能。

**Comment by wzsx150** [comment]
我把每一步的汇编代码复制出来了：
=========== RAW ===========
040B0000 07DE8DA0 1E212800
040B0000 07DE8DA4 529C0009
040B0000 07DE8DA8 72A8F569
040B0000 07DE8DAC 1E220142
040B0000 07DE8DB0 1E220800
040B0000 07DE8DB4 D65F03C0

040B0000 07DE8DB8 18FDA40A
=========== ASM ===========
0x7DE8DA0:	FADD	S0, S0, S1
0x7DE8DA4:	MOVZ	W9, #0xE000
0x7DE8DA8:	MOVK	W9, #0x47AB, LSL #16
0x7DE8DAC:	SCVTF	S2, W10
0x7DE8DB0:	FMUL	S0, S0, S2
0x7DE8DB4:	RET

0x7DE8DB8:	LDR	W10, #0x7DE4238


=========== RAW ===========
040B0000 07DE8DBC 17FFFFF9
=========== ASM ===========
0x7DE8DBC:	B	#0x7DE8DA0


=========== RAW ===========
040B0000 07DE8DC0 18FDD94A
=========== ASM ===========
0x7DE8DC0:	LDR	W10, #0x7DE48E8


=========== RAW ===========
040B0000 07DE8DC4 17FFFFF7
=========== ASM ===========
0x7DE8DC4:	B	#0x7DE8DA0




=========== RAW ===========
040B0000 07DE8DC8 528000A9
040B0000 07DE8DCC B909EB29
040B0000 07DE8DD0 D65F03C0

040B0000 07DE8DD4 2D4FCE75
040B0000 07DE8DD8 1E27F015
040B0000 07DE8DDC 1E2042B6
040B0000 07DE8DE0 D65F03C0

040B0000 07DE8DE4 AA1803E2
040B0000 07DE8DE8 3944EA68
040B0000 07DE8DEC 7100811F
=========== ASM ===========
0x7DE8DC8:	MOVZ	W9, #0x5
0x7DE8DCC:	STR	W9, [X25, #0x9E8]
0x7DE8DD0:	RET

0x7DE8DD4:	LDP	S21, S19, [X19, #0x7C]
0x7DE8DD8:	FMOV	S21, #31.00000000
0x7DE8DDC:	FMOV	S22, S21
0x7DE8DE0:	RET

0x7DE8DE4:	MOV	X2, X24
0x7DE8DE8:	LDRB	W8, [X19, #0x13A]
0x7DE8DEC:	CMP	W8, #0x20

=========== RAW ===========
040B0000 07DE8DF0 540000A1
=========== ASM ===========
0x7DE8DF0:	B.NE	#0x7DE8E04


=========== RAW ===========
040B0000 07DE8DF4 BD40BF0B
040B0000 07DE8DF8 1E221001
040B0000 07DE8DFC 1E21096B
040B0000 07DE8E00 BD00BF0B
040B0000 07DE8E04 D65F03C0
=========== ASM ===========
0x7DE8DF4:	LDR	S11, [X24, #0xBC]
0x7DE8DF8:	FMOV	S1, #4.00000000
0x7DE8DFC:	FMUL	S11, S11, S1
0x7DE8E00:	STR	S11, [X24, #0xBC]
0x7DE8E04:	RET	




=========== RAW ===========
040B0000 07DE8E38 8B0C096B
040B0000 07DE8E3C 52800089
040B0000 07DE8E40 1B097D08
040B0000 07DE8E44 D65F03C0

040B0000 07DE8E48 1E201002
040B0000 07DE8E4C BD002122
040B0000 07DE8E50 D65F03C0
=========== ASM ===========
0x7DE8E38:	ADD	X11, X11, X12, LSL #2
0x7DE8E3C:	MOVZ	W9, #0x4
0x7DE8E40:	MUL	W8, W8, W9
0x7DE8E44:	RET

0x7DE8E48:	FMOV	S2, #2.00000000
0x7DE8E4C:	STR	S2, [X9, #0x20]
0x7DE8E50:	RET	

但是最后还是如图显示的结果代码：
<img width="1052" alt="bug反馈2" src="https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/19254531/2dd30b81-aaf8-4130-8a45-c6aa44849375">

从图里可以发现：
=========== RAW ===========
040B0000 07DE8DF0 540000A1
=========== ASM ===========
0x7DE8DF0:	B.NE	#0x7DE8E04
这段代码里的目标地址 0x7DE8E04 在后面的代码中有写入数据，但是输出的代码没有更新，所以说这里还是有问题的。


-----------------------------------------------------------------------------------------
另外关于我说的第二个问题，好像我又发现了另一个bug，如图：
<img width="1052" alt="bug反馈3" src="https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/19254531/07034c15-feab-4eec-80e2-6ddd727c8dff">
上图当代码标签间有空行间隔时，会找不到跳转的自定义代码的地址，然后该条（040B0000 0420F1DC 94EF66F7）就没有输出了，此时是有bug的。

<img width="1052" alt="bug反馈3-2" src="https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/19254531/49f60c79-78d4-4502-8059-8c6ba84074ca">
上图中代码中删除了空行，自定代码的地址就可以正常找到，并且正常的输出结果。

**Comment by wzsx150** [comment]
关于第三个问题，你说的需要用户选择的问题，个人觉得可以当需要用户选择介入时，可以暂停下来，变成步进形式，当选择完以后可以继续连续生成，也可以继续步进。
如果没有需要用户选择的部分，则直接一直生成到结束。

应该就是在你程序的代码中增加一个循环函数，中间需要手动处理地方就中断一下，然后还能继续循环执行到结束。准确的说也不能叫一键生成，应该是类似于连续点击生成的效果。

**Comment by zzpong** [comment]
> 我把每一步的汇编代码复制出来了： =========== RAW =========== 040B0000 07DE8DA0 1E212800 040B0000 07DE8DA4 529C0009 040B0000 07DE8DA8 72A8F569 040B0000 07DE8DAC 1E220142 040B0000 07DE8DB0 1E220800 040B0000 07DE8DB4 D65F03C0
> 
> 040B0000 07DE8DB8 18FDA40A =========== ASM =========== 0x7DE8DA0: FADD S0, S0, S1 0x7DE8DA4: MOVZ W9, #0xE000 0x7DE8DA8: MOVK W9, #0x47AB, LSL #16 0x7DE8DAC: SCVTF S2, W10 0x7DE8DB0: FMUL S0, S0, S2 0x7DE8DB4: RET
> 
> 0x7DE8DB8: LDR W10, #0x7DE4238
> 
> =========== RAW =========== 040B0000 07DE8DBC 17FFFFF9 =========== ASM =========== 0x7DE8DBC: B #0x7DE8DA0
> 
> =========== RAW =========== 040B0000 07DE8DC0 18FDD94A =========== ASM =========== 0x7DE8DC0: LDR W10, #0x7DE48E8
> 
> =========== RAW =========== 040B0000 07DE8DC4 17FFFFF7 =========== ASM =========== 0x7DE8DC4: B #0x7DE8DA0
> 
> =========== RAW =========== 040B0000 07DE8DC8 528000A9 040B0000 07DE8DCC B909EB29 040B0000 07DE8DD0 D65F03C0
> 
> 040B0000 07DE8DD4 2D4FCE75 040B0000 07DE8DD8 1E27F015 040B0000 07DE8DDC 1E2042B6 040B0000 07DE8DE0 D65F03C0
> 
> 040B0000 07DE8DE4 AA1803E2 040B0000 07DE8DE8 3944EA68 040B0000 07DE8DEC 7100811F =========== ASM =========== 0x7DE8DC8: MOVZ W9, #0x5 0x7DE8DCC: STR W9, [X25, #0x9E8] 0x7DE8DD0: RET
> 
> 0x7DE8DD4: LDP S21, S19, [X19, #0x7C] 0x7DE8DD8: FMOV S21, #31.00000000 0x7DE8DDC: FMOV S22, S21 0x7DE8DE0: RET
> 
> 0x7DE8DE4: MOV X2, X24 0x7DE8DE8: LDRB W8, [X19, #0x13A] 0x7DE8DEC: CMP W8, #0x20
> 
> =========== RAW =========== 040B0000 07DE8DF0 540000A1 =========== ASM =========== 0x7DE8DF0: B.NE #0x7DE8E04
> 
> =========== RAW =========== 040B0000 07DE8DF4 BD40BF0B 040B0000 07DE8DF8 1E221001 040B0000 07DE8DFC 1E21096B 040B0000 07DE8E00 BD00BF0B 040B0000 07DE8E04 D65F03C0 =========== ASM =========== 0x7DE8DF4: LDR S11, [X24, #0xBC] 0x7DE8DF8: FMOV S1, #4.00000000 0x7DE8DFC: FMUL S11, S11, S1 0x7DE8E00: STR S11, [X24, #0xBC] 0x7DE8E04: RET
> 
> =========== RAW =========== 040B0000 07DE8E38 8B0C096B 040B0000 07DE8E3C 52800089 040B0000 07DE8E40 1B097D08 040B0000 07DE8E44 D65F03C0
> 
> 040B0000 07DE8E48 1E201002 040B0000 07DE8E4C BD002122 040B0000 07DE8E50 D65F03C0 =========== ASM =========== 0x7DE8E38: ADD X11, X11, X12, LSL #2 0x7DE8E3C: MOVZ W9, #0x4 0x7DE8E40: MUL W8, W8, W9 0x7DE8E44: RET
> 
> 0x7DE8E48: FMOV S2, #2.00000000 0x7DE8E4C: STR S2, [X9, #0x20] 0x7DE8E50: RET
> 
> 但是最后还是如图显示的结果代码： <img alt="bug反馈2" width="1052" src="https://private-user-images.githubusercontent.com/19254531/324908217-2dd30b81-aaf8-4130-8a45-c6aa44849375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODk5MjAsIm5iZiI6MTcxMzg4OTYyMCwicGF0aCI6Ii8xOTI1NDUzMS8zMjQ5MDgyMTctMmRkMzBiODEtYWFmOC00MTMwLThhNDUtYzZhYTQ0ODQ5Mzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMzAxNTVhN2NjODFiNmZiNGUyM2E4YTdmYzJlYjhhMjYzYTlhMWY3Yzc1ZmYzNjkxN2NlYjE3YWRhZDRlMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0exF0ME3GOs0xyDrirqo6Ot_AGXpfS8WThsCcV8dVqQ">
> 
> 从图里可以发现： =========== RAW =========== 040B0000 07DE8DF0 540000A1 =========== ASM =========== 0x7DE8DF0: B.NE #0x7DE8E04 这段代码里的目标地址 0x7DE8E04 在后面的代码中有写入数据，但是输出的代码没有更新，所以说这里还是有问题的。
> 
> 另外关于我说的第二个问题，好像我又发现了另一个bug，如图： <img alt="bug反馈3" width="1052" src="https://private-user-images.githubusercontent.com/19254531/324913321-07034c15-feab-4eec-80e2-6ddd727c8dff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODk5MjAsIm5iZiI6MTcxMzg4OTYyMCwicGF0aCI6Ii8xOTI1NDUzMS8zMjQ5MTMzMjEtMDcwMzRjMTUtZmVhYi00ZWVjLTgwZTItNmRkZDcyN2M4ZGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZTc2ZWU0MzcyODE4Zjk4M2MwMzAyMmZhMGFlMzdlZDMwNTNmOGJkZTczODhiMWQyYjU0YTAzZTYyODJjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_ABymP9hm2Ef5ORbVAgVW4aGNgpHj94_ImAkLekhHM"> 上图当代码标签间有空行间隔时，会找不到跳转的自定义代码的地址，然后该条（040B0000 0420F1DC 94EF66F7）就没有输出了，此时是有bug的。
> <img alt="bug反馈3-2" width="1052" src="https://private-user-images.githubusercontent.com/19254531/324913623-49f60c79-78d4-4502-8059-8c6ba84074ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODk5MjAsIm5iZiI6MTcxMzg4OTYyMCwicGF0aCI6Ii8xOTI1NDUzMS8zMjQ5MTM2MjMtNDlmNjBjNzktNzhkNC00NTAyLTgwNTktOGM2YmE4NDA3NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYTExMzlhNWQwNDU0ZDAyNWQ3MTIyNjhkZGEyYTgwZmYwNjk2OTVjMGZkY2I0MGVmOTQ0MWYxZDZhNWI1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2U7b6y55-cQnNN6IvoWphmTUHCCPu6GuqVstncAAAI"> 上图中代码中删除了空行，自定代码的地址就可以正常找到，并且正常的输出结果。

感谢提供详细信息。从这些内容上看，的确存在bug，初步猜测可能是金手指间内容分割的问题。如果方便的话麻烦提供下新旧main文件以及金手指代码方便复现与修复bug。我最近比较忙，但这个bug和复现用文件（如果有的话）我会保留下来以后修。



> 关于第三个问题，你说的需要用户选择的问题，个人觉得可以当需要用户选择介入时，可以暂停下来，变成步进形式，当选择完以后可以继续连续生成，也可以继续步进。 如果没有需要用户选择的部分，则直接一直生成到结束。
> 
> 应该就是在你程序的代码中增加一个循环函数，中间需要手动处理地方就中断一下，然后还能继续循环执行到结束。准确的说也不能叫一键生成，应该是类似于连续点击生成的效果。

关于这点的话，我持保留意见。当然，如果能重新设计合适UI、保证新增功能按键合理分配、不会让用户困扰的话，也是一种好的处理手段。


不过最近几个月我比较忙，应该很难抽出时间修复bug代码，甚至连最新的解压文件key适配都没做。所以如果可以自行修复的话，欢迎pr~

**Comment by wzsx150** [comment]
感谢大佬回复，我搞的是怪物猎人16.0.0和16.0.1，这个main文件太大了，有300M+，既然你暂时不方便修复，那我这几天看看你的源代码，我研究一下，如果可以，我会提交PR。

但是我还不太熟悉switch金手指这块的，刚接触，所以有些问题不知道大佬放不方便解答一下。
1、main文件我如何导入ida pro中进行分析？有什么现成工具或者方法吗？我试了一些工具和方法，还没找到成功的方法。
2、对于我上面提供的 怪盗B 制作的金手指，我看他是在一段不存在代码的新地址上写入了代码，然后修改游戏代码去调用这个地址的代码，类似于这样的修改，我觉得可以实现很多复杂的功能。我的问题是，怎么样知道这个新地址的代码没有超界，没有超过代码段，同时其他程序不会写入这段地址。例如：
040B0000 07DE8DA0 1E212800        其中07DE8DA0是没有游戏代码的地址，可以用来存放自定义代码。
那我改成：
040B0000 07DE9DA0 1E212800
这样会不会有问题？我能不能通过什么工具或者手段看到游戏代码段的分段区间？好像IDA pro中就可以看到吧，这样我就可以把自定义代码放在一个游戏代码段中代码的尾部，该部分地址本来就没有代码，刚好可以用来放自定义代码。而且我看你的程序对不存在的地址也会输出一个地址段。

希望大佬能稍微点播一下，非常感谢。

**Comment by zzpong** [comment]
> 感谢大佬回复，我搞的是怪物猎人16.0.0和16.0.1，这个main文件太大了，有300M+，既然你暂时不方便修复，那我这几天看看你的源代码，我研究一下，如果可以，我会提交PR。
> 
> 但是我还不太熟悉switch金手指这块的，刚接触，所以有些问题不知道大佬放不方便解答一下。 1、main文件我如何导入ida pro中进行分析？有什么现成工具或者方法吗？我试了一些工具和方法，还没找到成功的方法。 2、对于我上面提供的 怪盗B 制作的金手指，我看他是在一段不存在代码的新地址上写入了代码，然后修改游戏代码去调用这个地址的代码，类似于这样的修改，我觉得可以实现很多复杂的功能。我的问题是，怎么样知道这个新地址的代码没有超界，没有超过代码段，同时其他程序不会写入这段地址。例如： 040B0000 07DE8DA0 1E212800 其中07DE8DA0是没有游戏代码的地址，可以用来存放自定义代码。 那我改成： 040B0000 07DE9DA0 1E212800 这样会不会有问题？我能不能通过什么工具或者手段看到游戏代码段的分段区间？好像IDA pro中就可以看到吧，这样我就可以把自定义代码放在一个游戏代码段中代码的尾部，该部分地址本来就没有代码，刚好可以用来放自定义代码。而且我看你的程序对不存在的地址也会输出一个地址段。
> 
> 希望大佬能稍微点播一下，非常感谢。

不客气。这代码我已经完全重构过，很整洁，还是挺好改的。祝你好运~
1. ida分析main需要额外插件，比如[SwitchIDAProLoader](https://github.com/pgarba/SwitchIDAProLoader)。
2. 推荐学习下内存分段基础，会有更详细了解。针对这个问题的话，不同内存段之间大概率存在空白区域，因此可以加入自己的代码；代码定位可参考[main_file](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/tree/Active-Branch/Interactive%20ASM%20Cheats%20Updater/utilities/main_file.py)。

**Comment by wzsx150** [comment]
收到了，谢谢，我正在着手修bug。
我先尝试编译exe，发现遇到一些问题，麻烦大佬解答一下，如果没时间不解答也无碍。
1、key.txt就是`prod.keys`是吧？
2、我使用你说明的命令打包exe时，会有缺少prod.keys或者key.txt的提示，然后按照路径提示放了prod.keys，就可以生成exe了。
错误提示节选：
```
16070 INFO: Looking for ctypes DLLs
16098 INFO: Analyzing run-time hooks ...
16103 INFO: Including run-time hook 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
16108 INFO: Processing pre-find module path hook _pyi_rth_utils from 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
16110 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
16113 INFO: Including run-time hook 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
16114 INFO: Including run-time hook 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
16117 INFO: Including run-time hook 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
16118 INFO: Including run-time hook 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
16123 INFO: Including run-time hook 'D:\\Python\\Python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_cryptography_openssl.py'
16127 INFO: Including run-time hook 'D:\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
16181 INFO: Looking for dynamic libraries
D:\Python\Python39\lib\site-packages\PyInstaller\isolated\keys.txt or C:\Users\wzsx150\.switch\prod.keys not found!
Please dump your keys using https://github.com/shchmue/Lockpick_RCM/releases
Press Enter to exit...
```

3、大佬你打包exe具体是使用的哪些参数？或者spec文件内容方便提供一下吗？
4、如果我用我电脑的环境打包出来的exe，理论上应该使用我安装的python库里的dll文件，对吧？

**Comment by zzpong** [comment]
调试bug不需要打包，直接运行代码即可。如果只是初步了解python的话，可能改起来比较费劲......

**Comment by wzsx150** [comment]
> 调试bug不需要打包，直接运行代码即可。如果只是初步了解python的话，可能改起来比较费劲......

大佬放心，我也有一些编程基础，一步一步来，我需要先了解你的程序的工作机制，然后再有针对的修改。一点一点解决遇到的问题，经过简单测试，好像打包的exe程序的nsz和18.0.0版的key有些兼容性问题。然后我又修改nsz模块的代码，好像可以兼容18.0.0的可以，顺便去搞个nsz的PR试试。

就不打扰大佬了，我先潜心研究几天，除非万不得已的问题再发消息。

**Comment by wzsx150** [comment]
> 调试bug不需要打包，直接运行代码即可。如果只是初步了解python的话，可能改起来比较费劲......

大佬放心，我也有一些编程基础，一步一步来，我需要先了解你的程序的工作机制，然后再有针对的修改。一点一点解决遇到的问题，经过简单测试，好像打包的exe程序的nsz和18.0.0版的key有些兼容性问题。然后我又修改nsz模块的代码，好像可以兼容18.0.0的可以，顺便去搞个nsz的PR试试。

就不打扰大佬了，我先潜心研究几天，除非万不得已的问题再发消息。
