### ISSUE TITLE
Missing file from readme?

### ISSUE THREAD

**Issue by slacksystem** [zzpong/Interactive-ASM-Cheats-Updater#12]
Hi there. Is your `README.md` out of date? In the building from source section it references `NSCodeUpdater.py` but I can't find that file anywhere in the repo, source code, or rar file in the release. Can you clarify how to build and/or run the code from source? Also it references a main.spec template but I could not find that either.

**Comment by zzpong** [comment]
Sorry, README.md updated now. Thanks for pointing it out~
