### ISSUE TITLE
"Assembly Codes" windows show nothing

### ISSUE THREAD

**Issue by Liserng** [zzpong/Interactive-ASM-Cheats-Updater#13]
version v1.1.1f

game sifu 

game version v1.22_1197 & v0.1

cheats:

[師父 Sifu v1.22 TID=01007B5017A12000 BID=CE14D183190A44D2]

[№ 1. 死亡計數保持0]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 000000C8
680F1000 00000000 00000000

[№ 2. 保持23歲]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 000000B8
680F1000 40400000 40400000

[№ 3. 最大生命值 500]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 00000058
680F1000 43FA0000 43FA0000
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 000012F8
780F0000 00000140
640F1000 00000000 43FA0000

[№ 4. 最大架式值存量 500]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 00000068
680F1000 43FA0000 43FA0000
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001250
780F0000 00000238
640F1000 00000000 43FA0000

[№ 5. 鎖定值存量 14]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 00000078
680F1000 41600000 41600000

[№ 6. 技巧值存量 14]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 00000088
680F1000 41600000 41600000

[№ 7. 無限吊墜能量]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 000000D8
680F1000 40A00000 40A00000

[№ 8. 積分 88888888]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 00000168
680F1000 4CA98AC7 4CA98AC7

[№ 9. 經驗值 88888]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 000000A8
680F1000 47AD9C00 47AD9C00

[№10. 經驗值倍率 15x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000008
780F0000 00000108
680F1000 41700000 41700000

[№11. 鎖定值獲取倍率 15x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000050
680F1000 41700000 41700000

[№12. 武器耐久倍率 5x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 000000C0
680F1000 40A00000 40A00000

[№13. 武器傷害倍率 5x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 000000D0
680F1000 40A00000 40A00000

[№14. 武器對對手架式造成影響倍率 5x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 000000E0
680F1000 40A00000 40A00000

[№15. 徒手攻擊傷害倍率 5x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 000000F0
680F1000 40A00000 40A00000

[№16. 徒手攻擊對對手架式影響倍率 5x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000100
680F1000 40A00000 40A00000

[№17. 殺敵獲得HP倍率 15x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000110
680F1000 41700000 41700000

[№18. 所受傷害倍率 1/5]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000120
680F1000 3E4CCCCD 3E4CCCCD

[№19. 所受武器傷害倍率 1/3]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000140
680F1000 3EAAAAAB 3EAAAAAB

[№20. 用武器擋格影響所受傷害倍率 1/10]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000150
680F1000 3E4CCCCD 3E4CCCCD

[№21. 成功躲避後獲得的鎖定值獎勵 2x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000060
680F1000 40000000 40000000

[№22. 成功躲避後獲得的架式值獎勵 2x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 000000A0
680F1000 40000000 40000000

[№23. 成功反擊後獲得的鎖定值獎勵 2x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000070
680F1000 40000000 40000000

[№24. 格擋對對手架式的加成 2x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000080
680F1000 40000000 40000000

[№25. 格擋對對手武器的加成 2x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 00000090
680F1000 40000000 40000000

[№26. 插眼對架式影響的加成 2x]
580F0000 09764160
580F1000 00000DF0
580F1000 00000038
580F1000 00000000
580F1000 00000030
580F1000 00000330
580F1000 00001258
580F1000 00000150
580F1000 00000000
780F0000 000000B0
680F1000 40000000 40000000

[此套金手指由 Eiffel2018 制作, 免費提供, 歡迎轉載, 敬請表明來源出處]

![1](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/61110959/2b1036ce-0214-44b7-aa4f-e5a04a0bf99b)
![2](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/61110959/a8f3e00f-32f3-4025-a4cc-41f0b4e24912)

**Comment by zzpong** [comment]
Because they are not "Assembly Codes", they are just pointers.
