### ISSUE TITLE
error when updating cheat

### ISSUE THREAD

**Issue by senttex1407** [zzpong/Interactive-ASM-Cheats-Updater#2]
program throws and error after trying to update this certain cheat after it processes 80000042(the button activator) @zzpong 
![image](https://user-images.githubusercontent.com/96842903/219514667-0fd137ab-ab15-451c-8051-bb86ff07a146.png)

**Comment by zzpong** [comment]
This error occurs when code address (here is 01878A60) is located outside of main.nso code part (30fps function is seated in nnsdk part, not main. Would not update due to security concerns). Remove these cheat parts and update others could be a better choice.

**Comment by senttex1407** [comment]
alright 
so how would i go about updating this 60fps mod?

**Comment by senttex1407** [comment]
alright, so how would i go about updating the mod?

**Comment by zzpong** [comment]
Sorry, updating mods is not supported currently.

**Comment by senttex1407** [comment]
ah well, this program is in its early stages so i figured that would be the answer, but thanks for taking your time and reaching out to tell me!

**Comment by zzpong** [comment]
It has been updated for several versions. Now it is fully operational on updating old asm(assembly) cheat codes to new version.
The example shown in this issue is memory modification code, not the asm one. It would be better to try updating some other asm codes.
Hope this would help in some way!
