### ISSUE TITLE
Tutorial to Dump Main File ?

### ISSUE THREAD

**Issue by genocidekyuubi** [zzpong/Interactive-ASM-Cheats-Updater#3]
Forgive me for asking stupid questions. How do you dump the main file? What do you mean by Main File ?

I know how to dump NSP or dump XCI. I can use NX Dump Tool and can use DBI. But I don't understand with Dump Main File ?

Can you explain in more detail?

**Comment by zzpong** [comment]
Main file is the executable game file dumped from NSP or XCI, which located in exefs folder.
It's dumped automatically if you use the latest version.

**Comment by genocidekyuubi** [comment]
> Main file is the executable game file dumped from NSP or XCI, which located in exefs folder. It's dumped automatically if you use the latest version.

so as far as i understand, i just need to load the nsp from the update file that i dumped, and the asm cheat updater latest version will extract the main file by itself, isn't that right?

**Comment by zzpong** [comment]
Yep, you are right.

**Comment by genocidekyuubi** [comment]
ok, thanks for confirming my answer. I will try to do the steps above. Thank you so much 🙏🏻🙂
