### ISSUE TITLE
window size cannot be adjusted

### ISSUE THREAD

**Issue by Sgbdk** [zzpong/Interactive-ASM-Cheats-Updater#5]
<img width="959" alt="Screenshot 2023-09-14 085155" src="https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/130059940/a12c4af1-42ee-4c5f-a5aa-4b69737356cc">
how do you adjust the window for the new cheat generated ?

**Comment by zzpong** [comment]
By dragging the frame boarders.
