### ISSUE TITLE
nsnsotool failed working

### ISSUE THREAD

**Issue by StevensND** [zzpong/Interactive-ASM-Cheats-Updater#6]
![Captura](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/45856578/d573144e-72da-4fae-984a-22bd89e5d7fb)

I am getting this error every single time I open a main file (new update, no matter what game it is). In previous updates of this tool this would happen 1 time every "X" mains open but not now. Now every time I open a main file I get this error and I have to reopen the main to get it fixed and know the BID.

This is quite annoying because before even if I got this error I could update the cheats without problems. Now I don't have the security that the cheats are being updated and until I don't open the main for the second time nothing happens.

Could you fix it or let me know what I'm doing wrong?.

Thanks.

**Comment by zzpong** [comment]
Sorry for the inconvenience.

This error only comes out when the command of nsnsotool failed work. When the nsnsotool failed (to decompress main files), the later process should not work.

I haven't met or heard about this issue and can't reproduce this. I'm sorry that you have to fix it on your own.

Here's some quick tips that may help:

- Do you run a MacOS or Linux system? Python's "subprocess.Popen" may have compatibility issues.

- If you run it on Windows, dose the tool have administrator authority?

And there's one best way to fix it once for all:
Download the raw code and run on you own PC. Set breakpoint to "interface.py":
![图片](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/8416883/bd04ff37-0767-4a1d-b3d8-173c87e7bd12)
 Code in the red box is the only thing you need to care.

Hope it helps.

**Comment by StevensND** [comment]
I run it on Windows without admin permissions. Should I run it this way?. 

Also I didn't understand how to do the "Set breakpoint" thing.

**Comment by zzpong** [comment]
I run it on Windows without admin permissions. Should I run it this way?
A: Yep, give both nsnsotool and the code updater admin permissions.

Also I didn't understand how to do the "Set breakpoint" thing.
A: It's something about programming. But it's fine if you don't understand.

Maybe you can send me the "CodeUpdaterLog.txt" in "Code Updater for Nintendo Switch/log" folder so I can check if anything I can help.

**Comment by StevensND** [comment]
I gave admin permissions but is not working. I still have the error.

[Here's the log](https://pastebin.com/wCWKxhJu)

**Comment by zzpong** [comment]
Thanks for the response.

From the log error "UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 24: illegal multibyte sequence", it seem that you are using a file directory containing non-English words. Maybe Latin or Arabic but I'm not sure.
Please move this tool to a English ONLY file directory and try again.

In most cases, it's your pc user name. C:/User Name that NOT English/...

**Comment by StevensND** [comment]
Pretty sure that's not the issue. I move the folder to Desktop, rename the folder to asmupdater and nothing. Same error.

This is the path: C:\Users\Stevens\Desktop\asmupdater

[New log](https://pastebin.com/BiEyBiTP)

**Comment by zzpong** [comment]
Could you tell me which kind of encode type your system use?
When the tool get "texts" from windows, it's encoded. Then the error appears as it cannot find a correct decoder.
Need to know the encode type from your region to fix this bug.

**Comment by StevensND** [comment]
How I can know that?. I'm Spanish if that help. Windows 10 😅

**Comment by zzpong** [comment]
Thx, working on it~

**Comment by zzpong** [comment]
Could you please try this one?
Tested on my computer, works fine.

[main_en.zip](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/files/13380158/main_en.zip)

**Comment by StevensND** [comment]
Not working ...

**Comment by zzpong** [comment]
Hmm, should be Á-Úá-ú problem. Just wait a sec.

**Comment by StevensND** [comment]
We have Á, ç, ü À ... 😅

![Captura](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/45856578/0bcadce0-c845-4ec7-a960-9e8349874925)

![spanish-mac-keyboard-layout-keyshorts](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/45856578/75d1e119-8a06-461e-a23b-05e51f8cf120)

**Comment by zzpong** [comment]
That's the problem 😅
I change the decode type manually to ''latin-1", hope it works.
[main_en.zip](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/files/13380408/main_en.zip)

And please screenshot this page when you loading some gampackage so I can know the real type you use:
![图片](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/8416883/e5a8e4e2-31e6-430a-a7e3-10afd844c179)

**Comment by StevensND** [comment]
Blank text

![Captura](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/45856578/3263f3cd-d86e-4a3e-8ca5-5875221280fa)

**Comment by zzpong** [comment]
Wow... So python don't know the encode type. But no worries! I have the final fix.
[main_en.zip](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/files/13380551/main_en.zip)

I remove a little bit function to make sure it works on your computer well.

**Comment by StevensND** [comment]
Ok. This one seems to work. Ty!

**Comment by zzpong** [comment]
Finally! Glad it helps~

**Comment by StevensND** [comment]
Yeah. I confirm it's working. I tested on 2 games and 0 issues now. 

If you do an update ... Will I have to do anything?

**Comment by zzpong** [comment]
Nope, I'll release the same one as you got.
Just enjoy the games~

**Comment by StevensND** [comment]
Cool. Thanks!!
