### ISSUE TITLE
problems with updating a special "cheat"

### ISSUE THREAD

**Issue by 20Phoenix** [zzpong/Interactive-ASM-Cheats-Updater#8]
Hello :)
I have a very nice cheat that is showing special address values on the fly while using an app in combination with EdiZon SE + Zing.
I still use this cheat but it hasn't been updated for newer NSP versions.
The result of the CheatsUpdater isn't working.
So I want to ask for help here.

That's a part of the cheat:

```
[Get RDRAM]
580F0000 00574FE8
580F1000 00000000
04000000 00AE44E0 0000002D

[1-IA Idle GPR-RA]
540C0000 005E32E0
A4C00400 00AE4634
9808F0C0
11050000 00AE4637 00000070
78081000 70000000
21000000

[1-Idle]
08000000 00AE4634 80000810 981191E0 
```

**Comment by zzpong** [comment]
Hi buddy~
Seems these codes are not assembly codes, they are memory values. CheatsUpdater cannot update these type of codes.
Please ask the code maker to update the codes manually.

**Comment by 20Phoenix** [comment]
Ah, I understand. Yes, this functional cheat takes values from the memory.
Thanks for the quick response. :)

**Comment by 20Phoenix** [comment]
Ah, I understand.
Yes, this functional cheat takes values from the memory. What a pity.
Thanks for the quick response. :)
