### ISSUE TITLE
请问下出现图片这种情况该怎么办

### ISSUE THREAD

**Issue by A-tiantian** [zzpong/Interactive-ASM-Cheats-Updater#9]
[►一击必杀]
04000000 00C72BC0 B9403801
04000000 00C72BC4 12800002
04000000 00C72BC8 6B02003F
04000000 00C72BCC C12C2BLC12C3O1
04000000 00C72BD0 1E214001
04000000 00C72BD4 1E212800
04000000 00C72BD8 D65F03C0
04000000 0097BF28 940BDB26

[►技能无冷却]
04000000 007397D0 1E2703E0
04000000 007F8A60 2A0003E0
04000000 009BC63C 1E2703E8
04000000 009BC928 1E2703E8

[►魔法物品掉落率10亿%]
04000000 00C72BDC 1281F7C2
04000000 00C72BE0 6B02003F
04000000 00C72BE4 54000040
04000000 00C72BE8 17E8B2A6
04000000 00C72BEC C14C4BLC14C4O0
04000000 00C72BF0 BD400D40
04000000 00C72BF4 D65F03C0
04000000 00C72BF8 4CBEBC20
04000000 0046FB38 14200C29

![屏幕截图 2024-01-14 162051](https://github.com/zzpong/Interactive-ASM-Cheats-Updater/assets/54916974/9778813f-a8f7-45f0-aa06-f37b45559dff)

**Comment by zzpong** [comment]
点击生成即可。
